service: start-workshop

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    hello: world # this is a hack for env plugin

  lambdaHashingVersion: 20201221
  region: us-east-1
  profile: flo

package:
  include:
    - .env

custom:
  envFiles:
    - env.yml

functions:
  hello:
    handler: handler.hello
    timeout: 30
    events:
      - http:
          path: api/hello
          method: get
          integration: lambda
          cors: true

plugins:
  - serverless-env-generator
  - serverless-offline
