service: start-workshop-eugene-test

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    hello: world # this is a hack for env plugin

  lambdaHashingVersion: 20201221
  region: us-east-1
  profile: workshop-test
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:*:*:table/${file(env.yml):${opt:stage, self:provider.stage}.FILE_LIST_TABLE}
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

package:
  include:
    - .env

custom:
  prune:
    automatic: true
    number: 2
  envFiles:
    - env.yml

functions:
  createItem:
    handler: api/dynamoDB/createItem.createItem
    timeout: 30
    events:
      - http:
          path: api/dynamoDB/createItem
          method: post
          integration: lambda
          cors: true
  getFilesList:
    handler: api/dynamoDB/getFilesList.getFilesList
    timeout: 30
    events:
      - http:
          path: api/dynamoDB/getFilesList
          method: get
          integration: lambda
          cors: true
  createFile:
    handler: api/s3/createFile.createFile
    timeout: 30
    events:
      - http:
          path: api/s3/createFile
          method: post
          integration: lambda
          cors: true

resources:
  Resources:
    FileList:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(env.yml):${opt:stage, self:provider.stage}.FILE_LIST_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(env.yml):${opt:stage, self:provider.stage}.BUCKET_NAME}

plugins:
  - serverless-prune-plugin
  - serverless-env-generator
  - serverless-offline
